"""initial schema

Revision ID: bc8a938bfda7
Revises: 
Create Date: 2026-06-11 01:37:20.154541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'bc8a938bfda7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")  # pgvector (D-1)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('algo', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=True)
    op.create_table('app_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'scope_id', 'key', name='uq_setting_scope_key')
    )
    op.create_index(op.f('ix_app_setting_key'), 'app_setting', ['key'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_key', sa.String(length=128), nullable=False),
    sa.Column('issuer', sa.String(length=64), nullable=False),
    sa.Column('name_masked', sa.String(length=128), nullable=False),
    sa.Column('birth_date', sa.String(length=8), nullable=False),
    sa.Column('sex', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_patient_key'), 'patients', ['patient_key'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('study_uid', sa.String(length=128), nullable=False),
    sa.Column('accession_no', sa.String(length=64), nullable=False),
    sa.Column('study_date', sa.String(length=8), nullable=False),
    sa.Column('study_time', sa.String(length=16), nullable=False),
    sa.Column('modality', sa.String(length=16), nullable=False),
    sa.Column('body_part', sa.String(length=64), nullable=False),
    sa.Column('study_desc', sa.String(length=256), nullable=False),
    sa.Column('clinical_info', sa.Text(), nullable=False),
    sa.Column('orthanc_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('emergency', sa.Boolean(), nullable=False),
    sa.Column('series_count', sa.Integer(), nullable=False),
    sa.Column('instance_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studies_accession_no'), 'studies', ['accession_no'], unique=False)
    op.create_index(op.f('ix_studies_body_part'), 'studies', ['body_part'], unique=False)
    op.create_index(op.f('ix_studies_modality'), 'studies', ['modality'], unique=False)
    op.create_index(op.f('ix_studies_patient_id'), 'studies', ['patient_id'], unique=False)
    op.create_index(op.f('ix_studies_status'), 'studies', ['status'], unique=False)
    op.create_index(op.f('ix_studies_study_date'), 'studies', ['study_date'], unique=False)
    op.create_index(op.f('ix_studies_study_uid'), 'studies', ['study_uid'], unique=True)
    op.create_table('ai_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('cost_input_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_sec', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_jobs_status'), 'ai_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_ai_jobs_study_id'), 'ai_jobs', ['study_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sr_json', sa.JSON(), nullable=False),
    sa.Column('narrative_text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('reviewed_by', sa.String(length=64), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_model', sa.String(length=64), nullable=False),
    sa.Column('ai_sources', sa.JSON(), nullable=False),
    sa.Column('diff_metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'version', name='uq_report_study_version')
    )
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_study_id'), 'reports', ['study_id'], unique=False)
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('series_uid', sa.String(length=128), nullable=False),
    sa.Column('modality', sa.String(length=16), nullable=False),
    sa.Column('series_desc', sa.String(length=256), nullable=False),
    sa.Column('instance_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_series_uid'), 'series', ['series_uid'], unique=True)
    op.create_index(op.f('ix_series_study_id'), 'series', ['study_id'], unique=False)
    op.create_table('report_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('chunk_seq', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=32), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('modality', sa.String(length=16), nullable=False),
    sa.Column('body_part', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_embeddings_body_part'), 'report_embeddings', ['body_part'], unique=False)
    op.create_index(op.f('ix_report_embeddings_modality'), 'report_embeddings', ['modality'], unique=False)
    op.create_index(op.f('ix_report_embeddings_report_id'), 'report_embeddings', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_embeddings_report_id'), table_name='report_embeddings')
    op.drop_index(op.f('ix_report_embeddings_modality'), table_name='report_embeddings')
    op.drop_index(op.f('ix_report_embeddings_body_part'), table_name='report_embeddings')
    op.drop_table('report_embeddings')
    op.drop_index(op.f('ix_series_study_id'), table_name='series')
    op.drop_index(op.f('ix_series_series_uid'), table_name='series')
    op.drop_table('series')
    op.drop_index(op.f('ix_reports_study_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_ai_jobs_study_id'), table_name='ai_jobs')
    op.drop_index(op.f('ix_ai_jobs_status'), table_name='ai_jobs')
    op.drop_table('ai_jobs')
    op.drop_index(op.f('ix_studies_study_uid'), table_name='studies')
    op.drop_index(op.f('ix_studies_study_date'), table_name='studies')
    op.drop_index(op.f('ix_studies_status'), table_name='studies')
    op.drop_index(op.f('ix_studies_patient_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_modality'), table_name='studies')
    op.drop_index(op.f('ix_studies_body_part'), table_name='studies')
    op.drop_index(op.f('ix_studies_accession_no'), table_name='studies')
    op.drop_table('studies')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_patients_patient_key'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_app_setting_key'), table_name='app_setting')
    op.drop_table('app_setting')
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
